### ISSUE TITLE
White page inbox

### ISSUE THREAD

**Issue by russokiwi** [trustedsec/specula#3]
Instead of inbox, a white page is displayed in Outlook.  The folder list is there as per normal, so are the ribons and if I switch to sent items or any other folder, all appears fine - it's only the inbox.  Otherwise C2 is working, receiving, executing queue, etc.  

What would be the cause? Thank-you!

**Comment by api0cradle** [comment]
Hi, 
So basically the inbox is no longer showing the emails at all? Do you have a screenshot?

Do you use fronting or other technology in front of the specula server? 
Have you tried going direct to the server and see if that makes a difference?

Whenever I had that issue before it was because of caching on the CDN or similar.

**Comment by russokiwi** [comment]
Hey, yes that is correct.  https://snipboard.io/QLGp3e.jpg 

Fronting is cloudflare then nginx, however a different client on the same network that's not domain joined doesn't have this issue connecting to the same c2 so it's can't be the CDN.  Logs in the c2 look ok too.

I would have though maybe it's to do with gpo lockdown of the machine that's having the issue maybe scriptblocking of sorts, etc.. but it's not because jobs are executing fine?

**Comment by api0cradle** [comment]
Hey,
this might be due to IE lockdown policies or similar in gpo as you mentioned. Do you have a fresh machine in the same domain so you can attempt to replicate the issue (or is it just this specific machine)? 

Another troubleshooting step could be to reset the IE zone policies on that specific machine. You can do that by finding "internet options" in the start menu and do the reset all zones to default level.
![image](https://github.com/user-attachments/assets/4cdf0fe4-e94a-4423-a427-f83a7a27ea91)

More info on reset of IE: https://support.microsoft.com/en-us/windows/change-or-reset-internet-explorer-settings-2d4bac50-5762-91c5-a057-a922533f77d5

**Comment by russokiwi** [comment]
I'm on an assessment, all buttons under IE settings are disabled / I have domain user rights, so I can't confirm right or wrong but am guessing you're right it is the zone settings.. pitty because the rest of the framework works fine, just no inbox view for the user which wouldn't make this practical in this environment.  I'm wondering if the C2 would function if I put the link not under inbox but say RSS-Feeds which I know aren't being used.  Would that work hypothetically? or would it need the user to hit RSS-Feeds shortcut first to trigger?

**Comment by api0cradle** [comment]
If you add this to the rss-feed the execution will only happen if the user visits that folder in Outlook (and seems unlikely that it will happen). 

You could experiment if there are certain settings in IE you can "downgrade" to make it work. Most of the IE settings live in HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2, however if they are managed by a GPO changing these might not have any effect.

**Comment by api0cradle** [comment]
Closing issue since this is settings on the client and not something that can be solved in the Specula tool. Feel free to ask more questions on our discord in the Specula channel [https://discord.com/invite/trustedsec](https://discord.com/invite/trustedsec)
